version: '3'

services:

  school-time:
    depends_on:
      - postgres

    build: .

    ports:
      - "8080:8080"

    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432

  postgres:

    image: "postgres"

    environment:
      - POSTGRES_DB=schooltime
      - POSTGRES_USER=vaporschool
      - POSTGRES_PASSWORD=a3eilm2s2y

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - postgres
    command: postgres:5432
